### ISSUE TITLE
[BUG] - migrations created non-deterministically

### ISSUE THREAD

**Issue by suranyami** [liveshowy/webauthn_components#60]
# Description

Migrations are generated out of correct order, with the `users` table created after the migrations that depend on them.

## Steps To Reproduce

1. Run `mix wac.install` on a newly-generated Phoenix app, using Elixir 1.15.x.
2. Generated migrations will (sometimes?) appear with the `users` table generated *after* the associated tables that require foreign key associations to that table. See listing:

```sh
priv/repo/migrations
❯
ls
.rw-r--r--  52 djp staff 2023-11-28 11:38 .formatter.exs
.rw-r--r-- 667 djp staff 2023-11-28 11:42 20231128004224_user_keys.exs
.rw-r--r-- 461 djp staff 2023-11-28 11:42 20231128004225_user_tokens.exs
.rw-r--r-- 300 djp staff 2023-11-28 11:42 20231128004226_users.exs
```

4. Run `mix ecto.migrate`.
5. See error:

```sh
mix ecto.migrate
Compiling 15 files (.ex)
Generated example app

11:42:39.934 [info] == Running 20231128004224 Example.Repo.Migrations.CreateUserKeys.change/0 forward

11:42:39.935 [info] create table user_keys
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "users" does not exist
    (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:1161: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.11.0) lib/ecto/migration/runner.ex:348: Ecto.Migration.Runner.log_and_execute_ddl/3
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.11.0) lib/ecto/migration/runner.ex:311: Ecto.Migration.Runner.perform_operation/3
    (stdlib 3.17.2.4) timer.erl:166: :timer.tc/1
    (ecto_sql 3.11.0) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8
```

## Expected behavior

`users` table should always be created first.

## AdditionalCcontext

Elixir 1.15.7
Erlang 24.x

## Notify

- @type1fool
- @suranyami

**Comment by suranyami** [comment]
Above PR should resolve this issue.

**Comment by type1fool** [comment]
Thank you for reporting this bug. I see your PR, and I will be reviewing it shortly.
